application: getpushy
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /(.*\.html)
  static_files: static/\1
  upload: static/(.*\.html)
  
- url: /(icons.*)
  static_files: images/icons/\1
  upload: images/icons/(icons.*)
  
- url: /(placeholder.*)
  static_files: images/icons/\1
  upload: images/icons/(placeholder.*)
  
- url: /(.*\.(eot|ttf|woff))
  static_files: fonts/\1
  upload: static/(.*\.(eot|ttf|woff))
  
- url: /(.*\.png)
  static_files: images/touch/\1
  upload: images/touch/(.*\.png)

- url: /(meetup-worker.js)
  static_files: ./\1
  upload: /(meetup-worker.js)
  http_headers:
    Content-Type: application/javascript

- url: /(.*\.js)
  static_files: scripts/\1
  upload: scripts/(.*\.js)
  http_headers:
    Content-Type: application/javascript

- url: .*
  script: main.app
  login: optional

libraries:
- name: webapp2
  version: "2.5.2"
