application: google.com:mobile-meetup
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: .*
  script: main.app
  login: optional

libraries:
- name: webapp2
  version: "2.5.2"
